#!/bin/sh
#
# Regression test: the library's ABI must match the committed baseline.
#
# The baseline lives in abi/libasdf-<arch>.abi and is generated by abidw from
# libabigail, and is architecture specific.  Hosts with no checked in baseline
# skip.
#
# A failure means one of two things:
#
#   1. An ABI change was introduced unintentionally.  Look at the diff.
#
#   2. An ABI change was introduced deliberately, in which case three things
#      have to happen together, and this test's output says which:
#        - LIBASDF_VERSION_INFO in configure.ac (and the CMake variables
#          derived from it) must move; see docs/development.rst
#        - the history block in configure.ac gains a line saying what changed
#        - the baseline is regenerated with `make update-abi`
# Usage:
#
# Run with --update to rewrite the baseline instead of checking it.
#
# Exit code 77 (automake's SKIP code) is returned where there is nothing
# meaningful to check, unless the environment variable ASDF_TEST_ABI_STRICT=1
# is passed in--then the test *must* pass.

skip_code=77;
skip_msg="skipping"
if [ "$ASDF_TEST_ABI_STRICT" = "1" ]; then
  skip_code=1;
  skip_msg="failed"
fi

skip_or_die() {
  msg="$1"
  echo "${msg}; ${skip_msg}"
  exit ${skip_code}
}

update=0
if [ "${1:-}" = "--update" ]; then
  update=1
fi

if [ -z "${top_builddir}" ]; then
  top_builddir=".."
fi

if [ -z "${top_srcdir}" ]; then
  top_srcdir="${top_builddir}"
fi

arch=$(uname -m 2>/dev/null || echo unknown)
baseline="${top_srcdir}/abi/libasdf-${arch}.abi"

for tool in abidw abidiff; do
  if ! command -v "${tool}" > /dev/null 2>&1; then
    skip_or_die "${tool} not available (install abigail-tools)"
  fi
done

# Locate the shared library.  The automake and CMake builds put it in
# different places, and only ELF platforms are described by an abidw dump.
lib=""
for candidate in \
    "${top_builddir}"/.libs/libasdf.so \
    "${top_builddir}"/src/libasdf.so; do
  if [ -f "${candidate}" ] || [ -L "${candidate}" ]; then
    lib="${candidate}"
    break
  fi
done

if [ -z "${lib}" ]; then
  skip_or_die "no ELF shared libasdf found under ${top_builddir}"
fi

tmp=$(mktemp "${TMPDIR:-/tmp}/libasdf-abi.XXXXXX") || exit ${skip_code}
trap 'rm -f "${tmp}"' EXIT HUP INT TERM

# These flags decide what the ABI *is*, and must be identical on both sides of
# the comparison -- which is why generating and checking live in one script.
#
#   --no-show-locs / --no-comp-dir-path  strip host-specific paths, so the
#       baseline is reproducible on any machine
#   --headers-dir + --drop-private-types restrict the dump to types declared
#       in the public headers (--drop-private-types does nothing on its own)
#   --exported-interfaces-only           restrict to the dynamic symbol table
#   --type-id-style hash                 content-derived type ids, so an
#       inserted type does not renumber every entry after it
# The sed strips AddressSanitizer's ODR-violation aliases (__odr_asan.<name>,
# one per global) from the symbol table.  They are build instrumentation, not
# ABI.
abidw --no-show-locs --no-comp-dir-path --no-corpus-path \
      --drop-private-types --headers-dir "${top_srcdir}/include" \
      --exported-interfaces-only --type-id-style hash \
      "${lib}" 2>/dev/null \
  | sed -e "/<elf-symbol name='__odr_asan\./d" > "${tmp}"

if [ ! -s "${tmp}" ]; then
  skip_or_die "abidw produced nothing for ${lib}"
fi

# Without debug info abidw sees only the symbol table: signature and struct
# layout changes become invisible, and abidiff then reports "no change"
# rather than "cannot tell".  Refusing to run is the only safe response, as
# a false positive here would be worse than no test at all.
if ! grep -q '<function-decl ' "${tmp}"; then
  echo "${lib} carries no usable debug info, so only its symbol names could"
  echo "be compared; signature and layout changes would pass unnoticed."
  skip_or_die "Build with -g (e.g. --enable-debug) to run this test"
fi

if [ "${update}" -eq 1 ]; then
  mkdir -p "${top_srcdir}/abi" || exit 1
  cp "${tmp}" "${baseline}" || exit 1
  # mktemp creates 0600; this file is committed and read by everyone.
  chmod 644 "${baseline}" || exit 1
  echo "Wrote ${baseline}"
  exit 0
fi

if [ ! -f "${baseline}" ]; then
  echo "no ABI baseline for ${arch} at ${baseline}"
  skip_or_die "(generate one with \`make update-abi\` on this architecture)"
fi

diff_out=$(abidiff "${baseline}" "${tmp}" 2>&1)
rc=$?

if [ "${rc}" -eq 0 ]; then
  echo "Test passed: ABI matches ${baseline}"
  exit 0
fi

# abidiff's exit status is a bit field: 1 error, 2 usage error,
# 4 ABI changed, 8 ABI changed incompatibly.
if [ $((rc & 3)) -ne 0 ]; then
  echo "abidiff failed to run (exit ${rc}):"
  echo "${diff_out}" | sed -e 's/^/    /'
  exit 1
fi

echo "Test failed: the ABI no longer matches ${baseline}"
echo ""
echo "${diff_out}" | sed -e 's/^/    /'
echo ""

if [ $((rc & 8)) -ne 0 ]; then
  echo "This is an INCOMPATIBLE change: something was removed or altered, so"
  echo "existing binaries linked against libasdf will break.  If deliberate,"
  echo "the interface version must move with age reset to 0:"
  echo ""
  echo "    current++, revision = 0, age = 0     (the SONAME will change)"
else
  echo "This is a compatible change: interfaces were added, none removed or"
  echo "altered.  If deliberate, the interface version must move:"
  echo ""
  echo "    current++, revision = 0, age++       (the SONAME stays the same)"
fi

echo ""
echo "Then, in the same commit:"
echo "  - update LIBASDF_VERSION_INFO in configure.ac, and PROJECT_SOVERSION"
echo "    and PROJECT_LIBVERSION in CMakeLists.txt to match"
echo "  - add a line to the ABI history comment in configure.ac saying what changed"
echo "  - regenerate this baseline with \`make update-abi\`"
echo ""
echo "See \"Shared library versioning\" in docs/development.rst."
exit 1
