name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      make_flags:
        description: Extra flags to pass to make
        required: false
        default: ''

jobs:
  build-and-test:
    name: Build and run `make check`
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            build-essential \
            libfyaml-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install \
            autoconf \
            automake \
            libtool \
            argp-standalone \
            libfyaml

      - name: Bootstrap autotools
        run: ./autogen.sh

      - name: Configure
        run: ./configure

      - name: Build
        run: make ${{ github.event.inputs.make_flags }}

      - name: Check
        run: make check ${{ github.event.inputs.make_flags }}

